name: spm_demo
options:
  bundleIdPrefix: com.mmark
  deploymentTarget:
    iOS: "15.0"

packages:
  MMarkParser:
    path: ../MMarkParser

targets:
  spm_demo:
    type: application
    platform: iOS
    sources:
      - spm_demo
    dependencies:
      - package: MMarkParser
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mmark.spmdemo
        SWIFT_VERSION: "5.7"
        INFOPLIST_FILE: spm_demo/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
