name: Demo
options:
  bundleIdPrefix: com.mmark
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

targets:
  Demo:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Demo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mmark.demo
        SWIFT_VERSION: "5.7"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: ""
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        OTHER_LDFLAGS: "-ObjC"
